export const addCartItemCount = 'addCartItemCount'
export const reduceCartItemCount = 'reduceCartItemCount'
export const handelItemCheckedChange = 'handelItemCheckedChange'
export const handleCartAllChecked = 'handleCartAllChecked'
export const addToCart = 'addToCart'
export const handleIsShowBack = 'handleIsShowBack'
